### ISSUE TITLE
Unable to build site in a Windows 10 environment

### ISSUE THREAD

**Issue by miqid** [nodeschool/nodeschool.github.io#421]
I'm trying to execute `npm install` to build the site, but I run into an error with the `posix` module. Relevant environment details include:

- Windows 10 Pro (x64)
- Node v0.12.7
- Visual Studio Community 2015
- Python 2.7.10

After a quick search for an answer, I came across nodejs/node-gyp#679, which had some helpful suggestions to try assorted environment configurations to get `node-gyp` to rebuild properly. I tried out each combination one by one but didn't have any luck.

I noticed when I bumped up my version of Node to v4.x, I get the same failures described in #419.

When executing an `npm install` with the environment I listed above, the main error of interest appears to be:

    ..\src\posix.cc(2): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [F:\Code\projects\nodeschool.github.io\node_modules\posix\build\posix.vcxproj]

I tried obtaining `unistd.h` (and later `getopt.c` and `getopt.h`) to stash along with the rest of VC++ includes, but hit a road block when something was depending on `sys/resources.h`, something POSIX that I can't find a Windows port for.

Has anybody else run into this problem and knows if I'm missing something glaringly obvious?

**Comment by martinheidegger** [comment]
@miqid: Would you mind to send the whole error stack trace?

**Comment by miqid** [comment]
@martinheidegger, sure thing. Please see below.

```
$ npm install --msvs_version=2015
npm WARN package.json nodeschool.github.io@1.0.0 license should be a valid SPDX license expression

> posix@2.0.1 install F:\Code\projects\nodeschool.github.io\node_modules\posix
> node-gyp rebuild


F:\Code\projects\nodeschool.github.io\node_modules\posix>if not defined npm_config_node_gyp (node "C:\Dev\nvm\v0.12.7\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  posix.cc
..\src\posix.cc(2): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [F:\Code\projects\nodeschool.github.io\node_modules\posix\build\posix.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Dev\nvm\v0.12.7\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Dev\\nvm\\v0.12.7\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Code\projects\nodeschool.github.io\node_modules\posix
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Dev\\nodejs\\node.exe" "C:\\Dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2015"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! posix@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@2.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Code\projects\nodeschool.github.io\npm-debug.log
```

I also wanted to investigate further by looking into the `posix` module folder inside the project, but it does not exist, presumably due to the failure I'm having.

**Comment by No9** [comment]
Hi @miqid 
I just tried a `npm install posix` on my windows machine and I see that it fails with a similar error 
`fatal error C1083: Cannot open include file: 'unistd.h'`

I had a look at the code and the headers in posix.cc are unix specific and are not easily ported to windows. 

I would be very surprised if this project ever worked on windows.

**Comment by miqid** [comment]
@No9, thanks for the input.

If indeed the site can only be built inside of UNIX-like environments, I believe there should be a task to update the repository README to reflect this to spare other Windows users a wild goose chase in getting the build to work.

Alternatively, the site dependencies could be revised such that `posix` is no longer required, which would hopefully enable builds for Windows environments.

I'll probably go spin up a virtual machine to get the site building, but in the meanwhile I'm still interested in hearing what others might have to say.

**Comment by martinheidegger** [comment]
This issue will be solved by solving https://github.com/nodeschool/nodeschool.github.io/issues/419

**Comment by martinheidegger** [comment]
Opened PR #454 which should solve this issue.

**Comment by martinheidegger** [comment]
Should be fixed
